### ISSUE TITLE
Update project to nativescript 3.0

### ISSUE THREAD

**Issue by micaelr95** [micaelr95/DynamicApp#2]

**Comment by hugoroxas** [comment]
cadê publicidade

**Comment by micaelr95** [comment]
![hqdefault](https://cloud.githubusercontent.com/assets/12500655/26499883/fea885f4-422b-11e7-84e4-54994a77a083.jpg)

**Comment by micaelr95** [comment]
Como é que estão as cenas por
![prepare-your-anus-memegenerator-net-12914204](https://cloud.githubusercontent.com/assets/12500655/26500615/6f926f80-422e-11e7-89d1-89adf7f9d657.png)
 aí

**Comment by micaelr95** [comment]
Aqui novidades

**Comment by micaelr95** [comment]
@lbernasl Hello there

**Comment by lbernasl** [comment]
@micaelr95 goodbye there

**Comment by hugoroxas** [comment]
![image](https://cloud.githubusercontent.com/assets/1615234/26500924/ccbb8fce-422f-11e7-8658-53a3ca5a7bd4.png)

**Comment by LuisFranciscoCode** [comment]
https://github.com/PeterStaev/NativeScript-Drop-Down/issues/85
https://github.com/bradmartin/nativescript-checkbox/issues/33

**Comment by micaelr95** [comment]
Form, ListView and webview not working

**Comment by micaelr95** [comment]
Everything work except radio button and checkbox
